tracking/static/sss/sss.js
tracking/templates/index.html

Increase localforage's version to 1.4.0
Remove defr attribute for jquery.js and mapbox.js

Set the crs to EPSG:4326

---

resource_tracking/api.py
resource_tracking/settings.py
resource_tracking/templatetags/autoversion.py
resource_tracking/urls.py
tracking/admin.py
tracking/api.py
tracking/urls.py
tracking/views.py
weather/admin.py
weather/api.py
weather/apps.py
weather/migrations/0001_initial.py
weather/models.py
weather/templates/weather/index.html
weather/templates/weather/station.html
weather/urls.py
weather/utils.py
weather/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/12)

Import Weather Observations app, refactor API and URLs

---

requirements.txt
weather/tasks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/13)

Added requirements for weather/tasks.py.

---

weather/management/commands/download_weather_data.py
weather/tasks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/14)

Renamed task cron to download_data

---

requirements.txt
tracking/api.py
tracking/urls.py
tracking/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/15)

Altered DeviceResource to allow age filtering, added CSV download view.

---

tracking/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/16)

Bugfix: forget to pass cookies in internal API call.

---

requirements.txt
weather/templates/weather/index.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/19)

Update weather index template to use relative HTTP request.

---

weather/models.py
weather/tasks.py
weather/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/21)

Fix bug in WeatherObservation get_rainfall method. Refactor dafwa_obs utility function into utils.py.

---

weather/admin.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/22)

Define URL for OpenLayers.js to DPaW CDN.

---

resource_tracking/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/23)

Update logging config to rotate files at 5 Mb.

---

requirements.txt
weather/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/26)

Refactor last_reading_local, last_reading_time and rain_since_nine_am to use pytz

---

weather/templates/weather/station.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/27)

Weather station detail template heading URL should be weather index view

---

weather/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/30)

Show active stations only on weather index view

---

weather/urls.py
weather/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/31)

Added observations_health view

---

weather/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/32)

Output correct observations/hour in observations_health view

---

weather/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/33)

Fix bug: apply station health error status correctly

---

tracking/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/37)

tracking: devices csv to use deviceid instead of id

---

pollstations.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/39)

Refactor pollstations.py (Station class).

---

pollstations.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/40)

Bugfix: instantiate Station with numeric interval.

---

pollstations.py
weather/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/41)

Refactor Vaisala data polling to be more lenient about observation data pattern

---

pollstations.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/42)

Update pollstations to include periodic check on currently-active weather stations

---

resource_tracking/settings.py
weather/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/44)

Added archive logging of observation data transmitted to DAFWA.

---

weather/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/45)

Refactor actual_rainfall to always return Decimal object to one d.p.

---

weather/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/46)

Refactor dafwa_obs and actual_rainfall to force 2 d.p. maximum.

---

weather/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/47)

Bugfix: can't multiply Decimal and float.

---

weather/management/commands/download_weather_data.py
weather/models.py
weather/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/48)

Moved dafwa_obs from utils to WeatherObservation, removed unused upload_data function from utils.

---

weather/models.py
weather/test_models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/49)

Added unit tests for weather model class methods.

---

.gitignore
pollstations.py
weather/management/commands/upload_cached_observations.py
weather/management/commands/write_observation.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/51)

Refactor to use SFTP to upload observation data via upload_cached_observations mgmt command

---

resource_tracking/harvest.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/53)

harvest: lon/lat check is valid (between -180,180,-90,90)

---

resource_tracking/settings.py
setup.cfg
weather/management/commands/upload_cached_observations.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/58)

Added dafwa_upload logging handler, plus logging to upload_cached_observations mgmt command

---

weather/api.py
weather/management/commands/write_observation.py
weather/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/59)

Alter FTP-uploaded observation file name format to include BoM abbrev.

---

pollstations.py
weather/api.py
weather/management/commands/write_observation.py
weather/models.py
weather/templates/weather/station.html
weather/test_models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/62)

Bugfix: weather station view was not filtering by station_id. Added short-circuit to WeatherStation save_observation method.

---

.travis.yml
weather/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/63)

Remove temp exception for Mitchell Plateau AWS wind direction.

---

.travis.yml
tracking/harvest.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/65)

Additional try/except checks in tracking harvest functions.

---

tracking/harvest.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/67)

update harvest for tracplus callsign change

---

weather/models.py
weather/test_models.py
weather/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/resource_tracking/70)

Updated WeatherStation.save_observation to use timestamp included in raw_data

---

requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/71)

Updated Django version to 1.11.10.

---

weather/templates/weather/index.html
weather/templates/weather/station.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/72)

Update refs of DPaW > DBCA. Update a couple of JS libs.

---

tracking/management/commands/sync_data.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/73)

Enchance the sync_data logic to ignore the invalid data

---

Dockerfile
pollstations.py
requirements.txt
resource_tracking/settings.py
tracking/harvest.py
weather/admin.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/78)

Update Dockerfile, settings conventions, remove custom OpenLayers.js

---

weather/templates/weather/index.html
weather/templates/weather/station.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/79)

Bugfix weather index template.

---

weather/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/81)

Observations health view should return last_reading in AWST.

---

tracking/harvest.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/84)

 Harvest: fix date format for mp70 (use US m/d/y) 

---

tracking/harvest.py
tracking/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/88)

FES resource updates

---

Dockerfile
tracking/harvest.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/90)

Update Dockerfile base image, add symbols map to save_tracplus method.

---

resource_tracking/api.py
resource_tracking/settings.py
resource_tracking/urls.py
tracking/templates/index.html
tracking/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/92)

Comment out weather app

---

tracking/admin.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/95)

admin.py updates

---

Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/108)

Update Dockerfile to make Python 3 the default in the built image.

---

tracking/harvest.py
tracking/management/commands/harvest_dfes_feed.py
tracking/management/commands/harvest_fleetcare_db.py
tracking/management/commands/harvest_tracking_email.py
tracking/management/commands/harvest_tracplus.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/109)

More-detailed standard output from tracking point harvest commands

---

tracking/harvest.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/111)

Additional error handling in harvest functions, switch logging for stdout.

---

requirements.txt
tracking/dbutils.py
tracking/harvest.py
tracking/management/commands/harvest_fleetcare_db.py
tracking/reharvest.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/115)

Add fleetcare reharvesting feature;

---

Dockerfile
requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/134)

Update Django to 2.2.22 and GDAL to 3.3.0

---

resource_tracking/settings.py
tracking/harvest.py
tracking/management/commands/harvest_dfes_feed.py
tracking/management/commands/harvest_fleetcare_db.py
tracking/management/commands/harvest_tracking_email.py
tracking/management/commands/harvest_tracplus.py
tracking/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/142)

Refactor logging output for all tracking harvest functions

---

poetry.lock
pyproject.toml
resource_tracking/api.py
resource_tracking/settings.py
resource_tracking/urls.py
tracking/apps.py
tracking/email_utils.py
tracking/harvest.py
tracking/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/148)

Refactor email harvest functions, remove unused project dependencies.

---

tracking/harvest.py
tracking/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/149)

Move parse_sbd method out of LoggedPoint and into separate function.

---

.github/workflows/docker-publish.yml
Dockerfile
poetry.lock
pyproject.toml
resource_tracking/middleware.py
resource_tracking/settings.py
resource_tracking/urls.py
resource_tracking/wsgi.py
tracking/api.py
tracking/geojsonviews.py
tracking/harvest.py
tracking/urls.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/150)

Update Python & Django versions, factor out dj-static, add Github build-image action.

---

kustomize/README.md
kustomize/base/deployment.yaml
kustomize/base/kustomization.yaml
kustomize/base/persistentvolumeclaim.yaml
kustomize/base/statefulset.yaml
kustomize/overlays/uat/deployment_uat_patch.yaml
kustomize/overlays/uat/ingress.yaml
kustomize/overlays/uat/kustomization.yaml
kustomize/overlays/uat/service.yaml
kustomize/overlays/uat/statefulset_uat_patch.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/151)

Add Kubernetes kustomize base resources and UAT overlay

---

tracking/admin.py
tracking/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/155)

Attempt to fix error re ADMINS must be list of 2-tuples

---

kustomize/base/kustomization.yaml
kustomize/overlays/uat/kustomization.yaml
poetry.lock
pyproject.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/163)

Update requests version to mitigate vuln in urllib3

---

.github/workflows/image-build-scan.yml
kustomize/overlays/prod/cronjob_harvest_emails.yaml
kustomize/overlays/prod/deployment_prod_patch.yaml
kustomize/overlays/prod/ingress.yaml
kustomize/overlays/prod/kustomization.yaml
kustomize/overlays/prod/persistentvolumeclaim_prod_patch.yaml
kustomize/overlays/prod/service.yaml
kustomize/overlays/prod/statefulset_prod_patch.yaml
poetry.lock
pyproject.toml
tracking/management/commands/harvest_tracking_email.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/167)

Update Django version to mitigrate SQL injection vulnerability

---

resource_tracking/settings.py
resource_tracking/urls.py
tracking/urls.py
tracking/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/168)

Bugfix (remove ADMINS from settings), homepage redirect

---

manage.py
poetry.lock
resource_tracking/wsgi.py
setup.cfg

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/170)

Update manage.py and wsgi.py in line with other projects, update dependency versions.

---

Dockerfile
poetry.lock
pyproject.toml
resource_tracking/settings.py
tracking/dblock.py
tracking/dbutils.py
tracking/harvest.py
tracking/management/commands/import_fleetcare_to_staging.py
tracking/reharvest.py
tracking/sqlviews.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/171)

Add import_fleetcare_to_staging mgmt command, update base Python minor version, update Poetry, switch to psycopg2

---

poetry.lock
pyproject.toml
tracking/admin.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/resource_tracking/179)

Add device type to list/detail views. Update Django minor version.
